name: Build/release

on: [push, release]

jobs:
  release:
    runs-on: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Test
        run: |
          echo foobar: ${{ github.ref == 'refs/heads/master' }}
          echo baz: type=${{ github.event.type }}

      - name: Build Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          build_script_name: "compile"
          args: -p=never
          release: false

      - name: Release snapshot
        uses: samuelmeuli/action-electron-builder@v1
        if: github.ref == 'refs/heads/main'
        env:
          EP_PRE_RELEASE: true
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          release: true

      - name: Release tag
        uses: samuelmeuli/action-electron-builder@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          release: true
