name: Build/release

on: push

jobs:
  prepare:
    runs-on: [ubuntu-latest]
    steps:
      - run: touch foo
      - run: ls -la

  release:
    needs: prepare
    runs-on: [ubuntu-latest]

    steps:
      - run: ls -la
