name: Build/release

on: push

jobs:
  release:
    runs-on: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: test
        run: gh --help || true

      - name: Delete stuff
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: gh release delete -y snapshot || true

      - name: Create stuff
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: gh release create -p -t "eb-test snapshot" -n "" snapshot
