name: Build/release

on: push

jobs:
  release:
    runs-on: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Delete stuff
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: hub release delete snapshot || true

      - name: Create stuff
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: hub release create -p -t "eb-test snapshot" snapshot
